qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 0 204
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 204 408
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 408 612
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 612 816
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 816 1020
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 1020 1224
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 1224 1428
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 1428 1632
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 1632 1836
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 1836 2040
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 2040 2244
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 2244 2448
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 2448 2652
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 2652 2856
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 2856 3060
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 3060 3264
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 3264 3468
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 3468 3672
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 3672 3876
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 3876 4080
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 4080 4284
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 4284 4488
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 4488 4692
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 4692 4896
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 4896 5100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 5100 5304
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 5304 5508
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 5508 5712
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 5712 5916
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 5916 6120
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 6120 6324
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 6324 6528
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 6528 6732
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 6732 6936
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 6936 7140
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 7140 7344
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 7344 7548
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 7548 7752
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 7752 7956
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 7956 8160
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 8160 8364
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 8364 8568
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 8568 8772
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 8772 8976
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 8976 9180
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 9180 9384
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 9384 9588
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 9588 9792
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 9792 9996
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh medresearch 9996 10161
