qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 0 40
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 40 80
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 80 120
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 120 160
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 160 200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 200 240
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 240 280
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 280 320
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 320 360
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 360 400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 400 440
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 440 480
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 480 520
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 520 560
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 560 600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 600 640
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 640 680
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 680 720
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 720 760
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 760 800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 800 840
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 840 880
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 880 920
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 920 960
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 960 1000
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1000 1040
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1040 1080
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1080 1120
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1120 1160
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1160 1200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1200 1240
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1240 1280
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1280 1320
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1320 1360
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1360 1400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1400 1440
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1440 1480
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1480 1520
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1520 1560
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1560 1600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1600 1640
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1640 1680
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1680 1720
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1720 1760
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1760 1800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1800 1840
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1840 1880
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1880 1920
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1920 1960
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_sge.sh youtube2text 1960 1970
