qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 0 363
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 363 726
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 726 1089
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 1089 1452
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 1452 1815
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 1815 2178
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 2178 2541
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 2541 2904
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 2904 3267
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 3267 3630
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 3630 3993
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 3993 4356
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 4356 4719
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 4719 5082
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 5082 5445
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 5445 5808
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 5808 6171
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 6171 6534
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 6534 6897
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 6897 7260
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 7260 7623
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 7623 7986
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 7986 8349
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 8349 8712
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 8712 9075
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 9075 9438
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 9438 9801
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh medresearch 9801 10161
