qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 0 71
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 71 142
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 142 213
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 213 284
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 284 355
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 355 426
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 426 497
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 497 568
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 568 639
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 639 710
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 710 781
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 781 852
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 852 923
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 923 994
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 994 1065
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1065 1136
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1136 1207
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1207 1278
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1278 1349
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1349 1420
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1420 1491
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1491 1562
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1562 1633
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1633 1704
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1704 1775
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1775 1846
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1846 1917
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/overfeat_predict_sge.sh youtube2text 1917 1970
