qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 0 62
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 62 124
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 124 186
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 186 248
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 248 310
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 310 372
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 372 434
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 434 496
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 496 558
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 558 620
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 620 682
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 682 744
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 744 806
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 806 868
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 868 930
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 930 992
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 992 1054
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1054 1116
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1116 1178
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1178 1240
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1240 1302
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1302 1364
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1364 1426
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1426 1488
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1488 1550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1550 1612
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1612 1674
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 test 1674 1724
