qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 0 63
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 63 126
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 126 189
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 189 252
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 252 315
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 315 378
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 378 441
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 441 504
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 504 567
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 567 630
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 630 693
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 693 756
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 756 819
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 819 882
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 882 945
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 945 1008
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1008 1071
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1071 1134
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1134 1197
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1197 1260
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1260 1323
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1323 1386
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1386 1449
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1449 1512
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1512 1575
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1575 1638
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1638 1701
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/plsang/codes/deeptest/deepcaffe_predict_scores_sge.sh trecvidmed10 devel 1701 1744
